// <auto-generated />
using System;
using API_Juliet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Juliet.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240430000857_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Juliet.Models.Bostad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Antalrum")
                        .HasColumnType("int");

                    b.Property<int>("Biarea")
                        .HasColumnType("int");

                    b.Property<int>("Boarea")
                        .HasColumnType("int");

                    b.Property<int>("Byggår")
                        .HasColumnType("int");

                    b.Property<int>("Driftkonstnad")
                        .HasColumnType("int");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("KommunId")
                        .HasColumnType("int");

                    b.Property<int?>("MäklareId")
                        .HasColumnType("int");

                    b.Property<int?>("Månadsavgift")
                        .HasColumnType("int");

                    b.Property<string>("Objektbeskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tomtarea")
                        .HasColumnType("int");

                    b.Property<int>("Utgångspris")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KommunId");

                    b.HasIndex("MäklareId");

                    b.ToTable("Bostäder");
                });

            modelBuilder.Entity("API_Juliet.Models.BostadBild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BildURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BostadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BostadId");

                    b.ToTable("BostadsBilder");
                });

            modelBuilder.Entity("API_Juliet.Models.BostadKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BildURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BostadKategorier");
                });

            modelBuilder.Entity("API_Juliet.Models.Kommun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kommuner");
                });

            modelBuilder.Entity("API_Juliet.Models.Mäklarbyrå", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logotyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Presentation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mäklarbyråer");
                });

            modelBuilder.Entity("API_Juliet.Models.Mäklare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BildURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Epostadress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MäklarbyråId")
                        .HasColumnType("int");

                    b.Property<string>("Telefonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MäklarbyråId");

                    b.ToTable("Mäklare");
                });

            modelBuilder.Entity("API_Juliet.Models.Bostad", b =>
                {
                    b.HasOne("API_Juliet.Models.BostadKategori", "BostadKategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Juliet.Models.Kommun", "Kommun")
                        .WithMany()
                        .HasForeignKey("KommunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Juliet.Models.Mäklare", "Mäklare")
                        .WithMany()
                        .HasForeignKey("MäklareId");

                    b.Navigation("BostadKategori");

                    b.Navigation("Kommun");

                    b.Navigation("Mäklare");
                });

            modelBuilder.Entity("API_Juliet.Models.BostadBild", b =>
                {
                    b.HasOne("API_Juliet.Models.Bostad", "Bostad")
                        .WithMany()
                        .HasForeignKey("BostadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bostad");
                });

            modelBuilder.Entity("API_Juliet.Models.Mäklare", b =>
                {
                    b.HasOne("API_Juliet.Models.Mäklarbyrå", "Mäklarbyrå")
                        .WithMany()
                        .HasForeignKey("MäklarbyråId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mäklarbyrå");
                });
#pragma warning restore 612, 618
        }
    }
}
